---
version: "2"

services:
  app:
    environment:
      K2HB_KAFKA_GROUP_ID: kafka-to-hbase-dev
      K2HB_KAFKA_TOPICS: "test-topic"
      K2HB_HBASE_NAMESPACE: "k2hb"
      K2HB_HBASE_COLUMN: "cf:data"
